### ISSUE TITLE
The cyprees closes automatically when the files are executed. cypress run

### ISSUE THREAD

**Issue by norvinino** [OutbreakResources/incidence#131]
@dirkschumacher @jrcpulliam The cyprees closes automatically when the files are executed. cypress run. Show the following error:
RangeError [ERR_HTTP_INVALID_STATUS_CODE] [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 99
    at ServerResponse.writeHead (_http_server.js:248:11)
    at ServerResponse.writeHead (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:239:8)
    at ServerResponse.write (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\compression\index.js:84:14)
    at Duplexify.ondata (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at Duplexify.emit (events.js:315:20)
    at Duplexify.Readable.read (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:483:26)
    at flow (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:939:34)
    at resume_ (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:918:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
 {
  code: 'ERR_HTTP_INVALID_STATUS_CODE'
}
RangeError [ERR_HTTP_INVALID_STATUS_CODE] [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 99
    at ServerResponse.writeHead (_http_server.js:248:11)
    at ServerResponse.writeHead (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\on-headers\index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:239:8)
    at ServerResponse.write (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\compression\index.js:84:14)
    at Duplexify.ondata (C:\Temp\vsts-agent-win-x64-2.177.1\_work\3\.cache\Cypress\6.2.0\Cypress\resources\app\packages\server\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:681:20)

**Comment by norvinino** [comment]
@richfitz @dirkschumacher @zkamvar Good day. Any answer please. Thanks.

**Comment by dirkschumacher** [comment]
I don't quite understand the problem. What does it have to do with the incidence package?

**Comment by norvinino** [comment]
@richfitz @caijun the error corresponds to the one that cypress closes and stops executing the test

**Comment by zkamvar** [comment]
This project is not in any way related to cypress io. It looks like @norvinino  was looking for this repository in which they opened an issue: https://github.com/cypress-io/cypress/issues/15221

I'm going to close this issue as off-topic.
